# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embeddingservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65mbeddingservice.proto\"%\n\x10\x45mbeddingRequest\x12\x11\n\tsentences\x18\x01 \x03(\t\"C\n\x16GetActionScoresRequest\x12\x0f\n\x07\x61\x63tions\x18\x01 \x03(\t\x12\x18\n\x10task_description\x18\x02 \x01(\t\"\'\n\x11\x45mbeddingResponse\x12\x12\n\nembeddings\x18\x01 \x01(\x0c\"6\n\x17GetActionScoresResponse\x12\x1b\n\x13\x63osine_similarities\x18\x01 \x03(\x02\x32\x8f\x01\n\x10\x45mbeddingService\x12\x35\n\x0cGetEmbedding\x12\x11.EmbeddingRequest\x1a\x12.EmbeddingResponse\x12\x44\n\x0fGetActionScores\x12\x17.GetActionScoresRequest\x1a\x18.GetActionScoresResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embeddingservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMBEDDINGREQUEST._serialized_start=26
  _EMBEDDINGREQUEST._serialized_end=63
  _GETACTIONSCORESREQUEST._serialized_start=65
  _GETACTIONSCORESREQUEST._serialized_end=132
  _EMBEDDINGRESPONSE._serialized_start=134
  _EMBEDDINGRESPONSE._serialized_end=173
  _GETACTIONSCORESRESPONSE._serialized_start=175
  _GETACTIONSCORESRESPONSE._serialized_end=229
  _EMBEDDINGSERVICE._serialized_start=232
  _EMBEDDINGSERVICE._serialized_end=375
# @@protoc_insertion_point(module_scope)
