# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import embeddingservice_pb2 as embeddingservice__pb2


class EmbeddingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEmbedding = channel.unary_unary(
                '/EmbeddingService/GetEmbedding',
                request_serializer=embeddingservice__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=embeddingservice__pb2.EmbeddingResponse.FromString,
                )
        self.GetActionScores = channel.unary_unary(
                '/EmbeddingService/GetActionScores',
                request_serializer=embeddingservice__pb2.GetActionScoresRequest.SerializeToString,
                response_deserializer=embeddingservice__pb2.GetActionScoresResponse.FromString,
                )


class EmbeddingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEmbedding(self, request, context):
        """Recieves Sentences and Returns Embeddings 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActionScores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedding,
                    request_deserializer=embeddingservice__pb2.EmbeddingRequest.FromString,
                    response_serializer=embeddingservice__pb2.EmbeddingResponse.SerializeToString,
            ),
            'GetActionScores': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActionScores,
                    request_deserializer=embeddingservice__pb2.GetActionScoresRequest.FromString,
                    response_serializer=embeddingservice__pb2.GetActionScoresResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EmbeddingService/GetEmbedding',
            embeddingservice__pb2.EmbeddingRequest.SerializeToString,
            embeddingservice__pb2.EmbeddingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetActionScores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/EmbeddingService/GetActionScores',
            embeddingservice__pb2.GetActionScoresRequest.SerializeToString,
            embeddingservice__pb2.GetActionScoresResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
