#!/bin/sh
#SBATCH --job-name=train_drrn_scienceworld_task_easy_28
#SBATCH -o logs_easy_100k/drrn-task-28_%j.txt
#SBATCH --time=20:00:00
#SBATCH --partition=gpu-long
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=40GB
#SBATCH -d singleton
#SBATCH --exclude=ials-gpu005

export JAVA_HOME=/home/hgolchha_umass_edu/jre1.8.0_341
export PATH=$JAVA_HOME/bin:$PATH

python train-scienceworld.py --num_envs=8 --max_steps=100000 --task_idx=28  --priority_fraction=0.50 --memory_size=100000 --simplification_str=easy --env_step_limit=100 --eval_freq=1000 --eval_set=test --output_dir=logs_easy_100k/drrn-task-28-test --historySavePrefix=logs_easy_100k/drrn-task-28-test/drrn-task28-results-seed0-test