#!/bin/sh
#SBATCH --job-name=drrn_task_easy_limit_10_100k
#SBATCH -o logs_easy_limit_actions_to_gold_100k_v2/drrn-task-10_%j.txt
#SBATCH --time=23:00:00
#SBATCH --partition=gpu-long
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=40GB
#SBATCH -d singleton
#SBATCH --exclude=gpu002,ials-gpu030,ials-gpu002

export JAVA_HOME=/home/hgolchha_umass_edu/jre1.8.0_341
export PATH=$JAVA_HOME/bin:$PATH

python train-scienceworld-limit-actions-to-gold-v2.py --num_envs=8 --max_steps=100000 --task_idx=10  --priority_fraction=0.50 --memory_size=100000 --simplification_str=easy --env_step_limit=100 --eval_freq=1000 --eval_set=test --output_dir=logs_easy_limit_actions_to_gold_100k_v2/drrn-task-10-test --historySavePrefix=logs_easy_limit_actions_to_gold_100k_v2/drrn-task-10-test/drrn-task10-results-seed0-test