#!/bin/sh
#SBATCH --job-name=train_drrn_scienceworld_task_13_20_21_22
#SBATCH -o logs_single_variation/drrn-task-13_20_21_22_%j.txt
#SBATCH --time=167:00:00
#SBATCH --partition=gpu-long
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=40GB
#SBATCH --exclude=ials-gpu002
#SBATCH -d singleton

export JAVA_HOME=/home/hgolchha_umass_edu/jre1.8.0_341
export PATH=$JAVA_HOME/bin:$PATH

python train-scienceworld-single-variation.py --num_envs=8 --max_steps=10000 --task_idx=13  --priority_fraction=0.50 --memory_size=100000 --env_step_limit=100 --eval_freq=1000 --eval_set=test --output_dir=logs_single_variation/drrn-task-13-test --historySavePrefix=logs_single_variation/drrn-task-13-test/drrn-task13-results-seed0-test
python train-scienceworld-single-variation.py --num_envs=8 --max_steps=10000 --task_idx=20  --priority_fraction=0.50 --memory_size=100000 --env_step_limit=100 --eval_freq=1000 --eval_set=test --output_dir=logs_single_variation/drrn-task-20-test --historySavePrefix=logs_single_variation/drrn-task-20-test/drrn-task20-results-seed0-test
python train-scienceworld-single-variation.py --num_envs=8 --max_steps=10000 --task_idx=21  --priority_fraction=0.50 --memory_size=100000 --env_step_limit=100 --eval_freq=1000 --eval_set=test --output_dir=logs_single_variation/drrn-task-21-test --historySavePrefix=logs_single_variation/drrn-task-21-test/drrn-task21-results-seed0-test
python train-scienceworld-single-variation.py --num_envs=8 --max_steps=10000 --task_idx=22  --priority_fraction=0.50 --memory_size=100000 --env_step_limit=100 --eval_freq=1000 --eval_set=test --output_dir=logs_single_variation/drrn-task-22-test --historySavePrefix=logs_single_variation/drrn-task-22-test/drrn-task22-results-seed0-test