#!/bin/sh
#SBATCH --job-name=train_drrn_scienceworld_task_25_26_27
#SBATCH -o logs/drrn-task-25_26_27_%j.txt
#SBATCH --time=167:00:00
#SBATCH --partition=gpu-long
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=40GB
#SBATCH --exclude=ials-gpu002
#SBATCH -d singleton

export JAVA_HOME=/home/hgolchha_umass_edu/jre1.8.0_341
export PATH=$JAVA_HOME/bin:$PATH

python train-scienceworld.py --num_envs=8 --max_steps=10000 --task_idx=25  --priority_fraction=0.50 --memory_size=100000 --env_step_limit=100 --eval_freq=500 --eval_set=test --output_dir=logs/drrn-task-25-test --historySavePrefix=logs/drrn-task-25-test/drrn-task25-results-seed0-test
python train-scienceworld.py --num_envs=8 --max_steps=10000 --task_idx=26  --priority_fraction=0.50 --memory_size=100000 --env_step_limit=100 --eval_freq=500 --eval_set=test --output_dir=logs/drrn-task-26-test --historySavePrefix=logs/drrn-task-26-test/drrn-task26-results-seed0-test
python train-scienceworld.py --num_envs=8 --max_steps=10000 --task_idx=27  --priority_fraction=0.50 --memory_size=100000 --env_step_limit=100 --eval_freq=500 --eval_set=test --output_dir=logs/drrn-task-27-test --historySavePrefix=logs/drrn-task-27-test/drrn-task27-results-seed0-test
